# Generated by Django 5.1.4 on 2024-12-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0002_topics_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='cid',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='topics',
            name='tid',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
