# Generated by Django 5.1.4 on 2024-12-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0003_topics_cid_topics_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='tid',
        ),
        migrations.AlterField(
            model_name='topics',
            name='cid',
            field=models.IntegerField(),
        ),
    ]
