# Generated by Django 5.1.4 on 2024-12-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chapter', '0006_rename_subject_chapters_sid'),
        ('Topic', '0004_remove_topics_tid_alter_topics_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Chapter.chapters'),
        ),
    ]
