# Generated by Django 5.1.4 on 2024-12-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chapter', '0004_remove_chapters_cid_alter_chapters_sid'),
        ('Learn', '0003_remove_subjects_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='sid',
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Learn.subjects'),
            preserve_default=False,
        ),
    ]
