# Generated by Django 5.1.4 on 2024-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chapter', '0005_remove_chapters_sid_chapters_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='subject',
            new_name='sid',
        ),
    ]
