# Generated by Django 5.1.4 on 2024-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='chapter',
            new_name='subjectname',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='topic',
        ),
        migrations.AddField(
            model_name='subjects',
            name='sid',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
