# Generated by Django 5.1.4 on 2024-12-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0002_rename_chapter_subjects_subjectname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sid',
        ),
    ]
